### PR TITLE
Added Rohit Kumar Saini profile ⚡

### PR DESCRIPTION
**Pull request by rockingrohit9639**

### CODE REVIEW

**Comment by coderjojo** [comment]
Can you resize the image as it's taking too much space

**Comment by rockingrohit9639** [comment]
> Can you resize the image as it's taking too much space

Should I compress the file size or just crop it.

**Comment by coderjojo** [comment]
> > Can you resize the image as it's taking too much space
> 
> Should I compress the file size or just crop it?

Just crop it.

**Comment by rockingrohit9639** [comment]
> > > Can you resize the image as it's taking too much space
> > 
> > 
> > Should I compress the file size or just crop it?
> 
> Just crop it.

I have cropped the image. Can you check it?

**Pull request merged**
