### PR TITLE
feat: Added [dhanola] profile

### PR DESCRIPTION
**Pull request by DHANOLA**
feat: Added [dhanola] profile

### CODE REVIEW

**Review by DHANOLA — COMMENTED** [review]
UPDATE THE README FILE ADING MY PROFILE PAGE

**Comment by coderjojo** [comment]
You need to crop the readme image according to size mentioned in contribution file.

**Comment by DHANOLA** [comment]
can i add two pictures one below another because my readme is not coming in the dimension specified

**Comment by DHANOLA** [comment]
changed the picture dimensions

**Pull request merged**
