### PR TITLE
⚡ Added BereketSemagn.md file for bereketsemagn profile

### PR DESCRIPTION
**Pull request by bereketsemagn**
https://github.com/bereketsemagn

### CODE REVIEW

**Comment by coderjojo** [comment]
No need to create new markdown file you can add your profile itself in existing `README.md` file in alphabetical order. Refer to contribution guild for more details.

**Comment by bereketsemagn** [comment]
Should be fixed now @coderjojo 
If not, could you help out a bit and explain what you mean?

**Comment by coderjojo** [comment]
You just have to add screenshot of your readme file in `EXAMPLES` folder and then update [readme](https://github.com/coderjojo/creative-profile-readme/blob/master/README.md) file with your detail and link to png file, you need to add your profile in alphabetical order under B section. (refer to other close pull request for more example) 

```html
    <details>
        <summary>Preview</summary>
        <img src="EXAMPLES/<Username>.png">
    </details>

**Comment by bereketsemagn** [comment]
Thanks for explaining, I've finished @coderjojo

**Pull request merged**
