### PR TITLE
Add KaranChandekar to Awesome Developer Profile

### PR DESCRIPTION
**Pull request by KaranChandekar**

### CODE REVIEW

**Comment by coderjojo** [comment]
Add just the readme section and follow contribution guide for correct image size.

**Comment by KaranChandekar** [comment]
Fix: updated to only readme section image

**Comment by coderjojo** [comment]
Still image is taking too much space on page, follow contribution guide for correct image size.

**Comment by KaranChandekar** [comment]
feat: updated readme image to 620px

**Pull request merged**
