### PR TITLE
feat: Added SynthesisDu profile

### PR DESCRIPTION
**Pull request by SynthesisDu**
:)

### CODE REVIEW

**Comment by SynthesisDu** [comment]
Although I noted the limitations on image sizes mentioned in CONTRIBUTING.md, I found several images in repo were already over 1M.

**Comment by SynthesisDu** [comment]
Since the image I added is within normal size, I think this should be acceptable.

**Comment by coderjojo** [comment]
Can you just crop the readme section image as it is taking too much space?

**Comment by coderjojo** [comment]
> Although I noted the limitations on image sizes mentioned in CONTRIBUTING.md, I found several images in repo were already over 1M.

Soon I will fix those large images so that it won't affect the loading time.

**Comment by SynthesisDu** [comment]
I croped the size. I wonder if that's what you mean? Or do you want me to change the ratio of length to width?

**Comment by coderjojo** [comment]
> I croped the size. I wonder if that's what you mean? Or do you want me to change the ratio of length to width?

Sorry for the confusion, the readme image should be max 640 px height and no need to compress the image.

**Comment by SynthesisDu** [comment]
I think this version meets the requirements 👍

**Pull request merged**
