### PR TITLE
Add gabriel xavier list

### PR DESCRIPTION
**Pull request by gabrielmxavier**
Adding my readme profile to the repository.

### CODE REVIEW

**Comment by coderjojo** [comment]
Don't change the content of  `CONTRIBUTING.md`

**Comment by gabrielmxavier** [comment]
Changes on CONTRUTING.md deleted.

**Review by coderjojo — CHANGES_REQUESTED** [review]
link to image preview is also broken

**Comment by gabrielmxavier** [comment]
link to image fixed.

**Comment by coderjojo** [comment]
Please open new PR and follow guidelines mentioned in `CONTRIBUTING.md`

**Pull request closed without merging**
