### PR TITLE
feat: changed image extensions + optimize + changed github action

### PR DESCRIPTION
**Pull request by FMGordillo**
# Rough comparison

## Before
image

## After

image

# Pendings

- [x] Convert images
- [x] Rename files in `README`
- [ ] Change Github action (to format file to `webp`?)

# How it was done (FYI)

Change `.extension` for the extension desired

1. Transform files 
`for f in *.extension; do cwebp "$f" -o "${f%.extension}.webp" ; done`

2. Remove old file
`for f in *.extension; do rm "$f" ; done`

- [Convert images to WebP source](https://linuxnightly.com/convert-png-images-to-webp-on-linux-with-commands/)
- [StackOverflow source](https://stackoverflow.com/questions/2297510/linux-shell-script-for-each-file-in-a-directory-grab-the-filename-and-execute-a)

### CODE REVIEW

**Comment by FMGordillo** [comment]
Question @coderjojo what could be best?

1. Warn the user that the repository accepts only `.webp` images
2. Transform non-webp images into `.webp`

Depending on your thoughts, we can add [the github action that you've mentioned](https://github.com/calibreapp/image-actions)

**Comment by coderjojo** [comment]
LGTM!

**Review by coderjojo — APPROVED** [review]
LGTM!

**Comment by coderjojo** [comment]
> Question @coderjojo what could be best?
> 
>     1. Warn the user that the repository accepts only `.webp` images
> 
>     2. Transform non-webp images into `.webp`
> 
> 
> Depending on your thoughts, we can add [the github action that you've mentioned](https://github.com/calibreapp/image-actions)

I have added [PR template](https://github.com/coderjojo/creative-profile-readme/blob/master/.github/pull_request_template.md) and also GitHub action which will compresses any webp  files in a pull request.

Thank You for your contribution 🚀

**Pull request merged**
