### PR TITLE
Add RayhanADev's Profile!

### PR DESCRIPTION
**Pull request by RayhanADev**
Hiya! I have a really neat black and white profile I've been working on for a while now. If you like it, do you think you might be able to add it to your list? Thanks!
~ Ray

### CODE REVIEW

**Review by RayhanADev — COMMENTED** [review]
All looks right :)

**Comment by coderjojo** [comment]
Resize the readme image to size mentioned in contribution file.

**Review by RayhanADev — COMMENTED** [review]
Made some fixes

**Comment by RayhanADev** [comment]
@coderjojo yep my bad, I cut the image into parts and recombined it/resized it into a single 640px height png.

**Pull request merged**
